export const FIREBASE_BASE_URL = "<INSERT_YOUR_FIREBASE_URL_HERE>";

export const FIREBASE_INGREDIENTS_URL = `${FIREBASE_BASE_URL}/ingredients.json`;

export const FIREBASE_SIGN_UP_URL = "<INSERT_YOUR_FIREBASE_SIGN_UP_URL_HERE>";

export const FIREBASE_SIGN_IN_URL = "<INSERT_YOUR_FIREBASE_SIGN_IN_URL_HERE>";
